//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_Final_Project.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class INVENTORYEntities4 : DbContext
    {
        public INVENTORYEntities4()
            : base("name=INVENTORYEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PRODUCTINFO> PRODUCTINFO { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<USERACCOUNT> USERACCOUNT { get; set; }
        public DbSet<vw_all_product_info> vw_all_product_info { get; set; }
        public DbSet<PURCHASE> PURCHASE { get; set; }
    
        public virtual ObjectResult<sp_ProductInfo_Result> sp_ProductInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProductInfo_Result>("sp_ProductInfo");
        }
    }
}
