//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBSYS_Final_Project.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_all_product_info
    {
        public int PRODUCTCODE { get; set; }
        public string PRODUCTNAME { get; set; }
        public string PRODUCTQNTY { get; set; }
        public string PRODUCTPRICE { get; set; }
    }
}
